### ISSUE TITLE
Store manager report view - backend

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#27]
Things to keep in mind:
1. Backend should track that user can come back to the main screen or the Review screen
2. [ √ ] Each row should be auto-saved after an edit
3. [ √ ] Track `completed` vs `in-progress` state for each row 

Sanity tests: 
1. Shouldn't be able to main screen or review once the report has been submitted and has moved into `warehouse` status
2. Make sure that the report is editable across multiple sessions with few rows being edited each time and then edit mode loading up with the right set of changes 
3. None of the completed items should show up in edit view and vice-versa 

![3 0-store-manager-report](https://cloud.githubusercontent.com/assets/1392314/7360454/ade38e88-ed10-11e4-9596-2458c18090e3.jpg)
![3 1-store-manager-report-add-comment](https://cloud.githubusercontent.com/assets/1392314/7360612/7e1e5528-ed12-11e4-883c-1ae0231c58ae.jpg)
![4 2-store-manager-report-review](https://cloud.githubusercontent.com/assets/1392314/7360616/8f381b46-ed12-11e4-92f2-edb8abd263ad.jpg)

**Comment by pulkitsinghal** [comment]
@Chhaya-rai - you finished these already, I think:
> Things to keep in mind:
...
2. Each row should be auto-saved after an edit
3. Track completed vs in-progress state for each row

@Chhaya-rai : so you'll be working on the following next:
> Sanity tests: 
...
3. None of the completed items should show up in edit view and vice-versa

**Comment by pulkitsinghal** [comment]
Qs for @srisub and @elbrando:

1. *Should* the `Review` button be disabled until all the rows have been moved to a `completed` state?
2. Otherwise, if `managers` can jump into the `review` screen at any point in time ... then *should* the `Submit` button be disabled until all the rows have been moved to a `completed` state?
3. Otherwise, if `managers` can click the `Submit` button even when all the rows have NOT been moved to a `completed` state ... then:
  1. *should* all the rows be automatically moved to a `completed` state and the report submitted?
  2. or, *should* all the rows that are at the `in-progress` state, be removed and the the report submitted with only the `completed` state rows?

**Comment by srisub** [comment]
@pulkitsinghal based on the following comment by @elbrando in the "Warehouzz" doc it looks like #1. 

No "Submit to Warehouse" button on Outlet's ReOrder page (will eventually be empty).
- "Review & Submit" button instead.

**Comment by elbrando** [comment]
2 would be better, as they *will* make mistakes and *should* correct those right away. 

1 is OK but not ideal.

3 to be avoided completely.

**Comment by pulkitsinghal** [comment]
Confirmed that 1 is ideal because rows in "Show Completed" can still be edited

**Comment by pulkitsinghal** [comment]
@elbrando - I need to come talk to you about how difficult it is to locate the row you may want to fix, once its been moved to completed, might want to use a different sorting order without grouping when viewing that state.
