### ISSUE TITLE
Changes to Create Manual Order supplier and store display options 

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#70]
1) For Order From (supplier), limit data in seed.json (and display) just the 2 active ones, FFCC and CSC. 
2) For Order To, show the list of outlets - currently it mistakenly shows the supplier list. If its a store manager logged in to Create the manual order, default the Order To value to the outlet which maps to the Store Manager's login.

**Comment by pulkitsinghal** [comment]
Updated the latest seed.json file (version 5) so that it will have only these suppliers: FFCC and CSC ... for those developers or devops folks with access to the folder which contains seed files, please get it from there for your respective builds.

I've already kicked off new builds for staging and production with v5 seed file.

**Comment by pulkitsinghal** [comment]
@srisub - please sanity test it when you get a chance ... or write an e2e protractor test ;)
