### ISSUE TITLE
Virtual keyboard doesn't pop up on ipad on store landing and report screens 

### ISSUE THREAD

**Issue by srisub** [ShoppinPal/warehouse#71]

**Comment by srisub** [comment]
![image](https://cloud.githubusercontent.com/assets/1392314/7966650/19f67aa0-0a43-11e5-8d74-29ea8afd8f3e.jpg)
![image](https://cloud.githubusercontent.com/assets/1392314/7966651/19faf7f6-0a43-11e5-93d2-8a40bd051459.jpg)

**Comment by srisub** [comment]
@elbrando Can you confirm if you are seeing this issue as well?

**Comment by pulkitsinghal** [comment]
@srisub and @ayushranjan-planetria  - it simply not wired ... also since the keyboard isn't very performant right now, @elbrando requested that:
a) it be decoupled from the login screen for now and only be attached to the comments until we figure out all of its performance issues
b) instead of attaching it at the very bottom like an ipad keyboard, put it immediately under the comments area like the module supports (see demo [here](http://the-darc.github.io/angular-virtual-keyboard/#demo)) ... if its an easy thing to do otherwise nevermind

**Comment by srisub** [comment]
Verified that its now only in the comment area
